config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  post "create_task", to: "lists#create_task"
  get 'home/trash_em'
  get 'home/trash_em_all'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def trash_em
    @trash_em = List.where(:completed => true).destroy_all
    redirect_to root_url, notice: 'All Marked Items Were Successfully Deleted'
  end

  def trash_em_all
    @trash_em_all = List.all.destroy_all
    redirect_to root_url, notice: 'All Items Were Sucessfully Deleted'
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_task
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!-- application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <link rel="icon" href="/android-chrome-192x192.png" sizes="192x192" type="image/png">
    <link rel="icon" href="/android-chrome-512x512.png" sizes="512x512" type="image/png">
    <link rel="icon" href="/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "lists/navbar" %>
    <div class="container">
      <%= yield %>
    </div>

    <!-- Adicione antes do </body> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/lists/_list.html.erb
<tbody>
  <% if list.completed %>
    <tr class="table-secondary">
      <td class="striker"><%= list.description %></td>
      <td>
        <center>
          <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden' %>
            <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
            <%= f.submit "Uncross", class: 'btn btn-outline-secondary btn-sm' %>
          <% end %>
        </center>
      </td>
      <td>
        <%= button_to "Delete", list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
      </td>
    </tr>
  <% else %>
    <tr>
      <td><%= list.description %></td>
      <td>
        <center>
          <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden' %>
            <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
            <%= f.submit "Cross Off", class: 'btn btn-outline-secondary btn-sm' %>
          <% end %>
        </center>
      </td>
      <td>
        <%= button_to "Delete", list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "To-do List", root_path, class: 'navbar-brand' %>

    <form class="d-flex align-items-center" action="<%= create_task_path %>" method="post">
      <input class="form-control me-2" type="search" placeholder="New Task" name="list[description]" aria-label="New Task" style="flex: 1;">
      <button class="btn btn-outline-secondary" type="submit">Add To-Do Item</button>
    </form>
  </div>
</nav>

app/views/lists/index.html.erb
<div class="container mt-4">
      <table class="table table-bordered">
        <tbody>
          <div id="lists">
            <% @lists.each do |list| %>
              <%= render partial: 'list', locals: { list: list } %>
            <% end %>
          </div>
        </tbody>
      </table>
</div>

<%= link_to 'Delete Marked Items', home_trash_em_path, class: "text-decoration-none text-reset p-2" %> |
<%= link_to 'Delete All Items', home_trash_em_all_path, class: "text-decoration-none text-reset p-2" %>